eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    preferIpAddress: true

logging:
  config: classpath:log4j2.xml

server:
  port: 8081
  servlet:
    context-path: /sample-web-api
  tomcat:
    uri-encoding: UTF-8

spring:
  aop:
    proxy-target-class: true
  application:
    name: sample-web-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  mvc:
    contentnegotiation:
      favor-path-extension: false
    pathmatch:
      use-registered-suffix-pattern: true
      use-suffix-pattern: false
    throw-exception-if-no-handler-found: true

  profiles:
    active: dev

  redis:
    jedis:
      database: 15
      host: 192.168.0.1
      password:
      port: 6379
      timeout: 3000
      pool:
        blockWhenExhausted: false
        max-idle: 30
        max-total: 1000
        maxWaitMillis: 60000
        min-idle: 5
        minEvictableIdleTimeMillis: 1800000
        numTestsPerEvictionRun: 1024
        softMinEvictableIdleTimeMillis: 10000
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 30000

# sample微服务url，如果不走注册中心时，必填此值
sample:
  server:
    url: